language: cpp
compiler: g++

sudo: required
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-7
- export CXX="g++-7"

script: ./tester/run_all_tests.sh
